version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "defect-guard"
s3_prefix = "defect-guard"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
